repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # ή όποια είναι η τελευταία συμβατή έκδοση
    hooks:
      - id: ruff
        args: [--fix]  # optional: κάνει αυτόματα διορθώσεις
